# SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: nixos
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint licensing
        run: nix develop -c reuse lint

  test:
    runs-on: nixos
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run tests
        run: nix develop -c zig build test

  publish:
    runs-on: nixos
    needs:
      - lint
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build docs
        run: nix develop -c zig build docs

      - name: Publish docs
        run: nix develop -c git-pages-cli https://jeff.ocj.page/zig-netbox/ --server ocj.page --token ${{ forge.token }} --upload-dir zig-out/docs
